# Generated by Django 3.1.1 on 2020-09-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pithub', '0002_auto_20200919_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в соц сети'),
        ),
    ]
